on: push
name: Test FTP Deploy
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@master
      with:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}     # FTPサーバーのURLを設定
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }} # FTPのユーザー名を設定
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }} # FTPのパスワードを設定
        LOCAL_DIR: app/bedrock/web/app/themes/kokusai # どのディレクトリのデータをアップロードするか
        REMOTE_DIR: /okinawa-futsal.com/public_html//wp-content/themes/kokusai # リモートのどのディレクトリにアップロードするか
        ARGS: --delete
        # --delete arg will delete files on the server if you've deleted them in git
